server:
  port: 9001

debug: false

spring:
  main:
    banner-mode: "off"
  application:
    name: cymirc
  datasource:
    url: jdbc:postgresql://localhost:5432/ezappxdev
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  devtools:
    livereload:
      enabled: false

logging:
  level:
    root: INFO
    com.ezappx: DEBUG

ezappx:
  mobile:
    builder:
      base-dir: ${HOME}/Projects/Ezappx/tmp
      project-dir-name: ${ezappx.mobile.builder.base-dir}/UserProjects
      package-name-prefix: com.ezappx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

info:
  app:
    name: ${spring.application.name}
    description: Ezappx mobile builder server
    version: 0.1

